version: "3.9"

services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile

    image: matcha-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: matcha
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    volumes:
      - "./postgres/.data:/var/lib/postgresql/data"

    secrets:
      - postgres_password

    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_messages=info"]

  front:
    image: nginx:1.23.3

    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
        mode: 644
        gid: "0"
        uid: "0"

    ports:
      - "8080:80"

    volumes:
      - "./front/dist:/app"

  redis:
    image: redis:7.0.7
    ports:
      - "6379:6379"

configs:
  nginx:
    file: nginx.conf

secrets:
  postgres_password:
    file: postgres_password